### ISSUE TITLE
Tag Latest Code on Main

### ISSUE THREAD

**Issue by boumenot** [ryanrolds/sqlclosecheck#10]
Would you be willing to tag the latest code in main?

I am using golangci-lint, and have been using your linter to good effect.  I recently hit a panic in this linter that I cannot reproduce against the latest code in main.  I would like to submit a PR to golangci-lint to update this linter, and I want to associate it with a tag.

**Comment by ldez** [comment]
@ryanrolds friendly ping

**Comment by ryanrolds** [comment]
I will take care of this on Saturday.

**Comment by ldez** [comment]
@ryanrolds friendly ping

**Comment by ldez** [comment]
friendly ping @ryanrolds

**Comment by ryanrolds** [comment]
The [v0.4.0](https://github.com/ryanrolds/sqlclosecheck/releases/tag/v0.4.0) should be used by `golangci-lint`.
