### ISSUE TITLE
Can this be made to work with pgx.Rows?

### ISSUE THREAD

**Issue by craigpastro** [ryanrolds/sqlclosecheck#23]
👋 I am using pgx directly and just tested if this works with pgx.Rows, but it seems it does not. Is this a feature that would be worth adding? At the moment I have no idea how this linter works, but, if you think this would be useful, I can perhaps help out. 

Thanks!

**Comment by craigpastro** [comment]
hmm, so the rows type in `pgx` is of type `pgx.Rows`, that is, not a pointer. As far as I can tell, this means that this is a bit more than a trivial change.

**Comment by hallabro** [comment]
This is something that has been on my lately as well so I opened a PR to add support for `pgx` here: https://github.com/ryanrolds/sqlclosecheck/pull/25.

Let me know if it works for you!

**Comment by ryanrolds** [comment]
I will take take a look at the PR by the end of the weekend.

**Comment by ryanrolds** [comment]
Requested some minor changes. I intend to merge this as soon as the changes are made. Great work @hallabro.
