### ISSUE TITLE
Minimun Go version

### ISSUE THREAD

**Issue by ldez** [ryanrolds/sqlclosecheck#30]
Is it possible for you to downgrade the version inside your `go.mod` to go1.20?

The new way to handle the module and Go version is strict.

https://github.com/golangci/golangci-lint/actions/runs/6094893861/job/16537363640

https://go.dev/blog/toolchain

https://github.com/golangci/golangci-lint/pull/4067

**Comment by ryanrolds** [comment]
Done.
